server:
  port: 8080
spring:
  application:
#    应用的名称
    name: take_out_hive

#mysql主从复制配置
  shardingsphere:
    datasource:
      names:
        master,slave
      # 主数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.127.101:3306/takeouthive?characterEncoding=utf-8
        username: root
        password: qwe2001cws
      # 从数据源
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.127.102:3306/takeouthive?characterEncoding=utf-8
        username: root
        password: qwe2001cws
    masterslave:
      # 读写分离配置
      load-balance-algorithm-type: round_robin
      # 最终的数据源名称
      name: dataSource
      # 主库数据源名称
      master-data-source-name: master
      # 从库数据源名称列表，多个逗号分隔
      slave-data-source-names: slave
    props:
      sql:
        show: true #开启SQL显示，默认false
  main:
      allow-bean-definition-overriding: true

  #redis配置
  redis:
    host: 192.168.127.100
    password: C201521cws
    port: 6379
    database: 0
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      #表示利用雪花算法来生成id值
      id-type: ASSIGN_ID

takeoutHive:
  path: D:\takeoutHive\src\main\resources\images\